---
- name: Initial Setup
  hosts: all
  remote_user: root
  tasks:

  - name: Add Kernel Modules to Load
    ansible.builtin.lineinfile:
      path: /etc/modules-load.d/k8s-bootstrap.conf
      state: present
      create: yes
      line: "{{ item }}"
    loop:
      - br_netfilter
      - overlay

  - name: Add sysctl params
    ansible.builtin.lineinfile:
      path: /etc/sysctl.d/k8s-bootstrap.conf
      state: present
      create: yes
      line: "{{ item }}"
    loop:
      - net.bridge.bridge-nf-call-iptables = 1
      - net.ipv4.ip_forward = 1
      - net.bridge.bridge-nf-call-ip6tables = 1

  - name: Add Kubernetes and Docker GPG apt keys
    ansible.builtin.apt_key:
      url: "{{ item }}"
      state: present
    loop:
      - https://packages.cloud.google.com/apt/doc/apt-key.gpg
      - https://download.docker.com/linux/debian/gpg
  
  - name: Add Kubeadm Repository
    ansible.builtin.apt_repository:
      repo: "{{ item }}"
      state: present
    loop:
        - deb https://apt.kubernetes.io/ kubernetes-xenial main
        - deb https://download.docker.com/linux/debian buster stable

  - name: Update all packages for Debian-like Systems
    ansible.builtin.apt:
      update_cache: yes
      name: '*'
      force_apt_get: yes
      state: latest
    when: ansible_facts['os_family'] == 'Debian'
    notify: Autoremove Packages using APT

  - name: Install necessary packages
    ansible.builtin.package:
      name:
        - curl
        - ifupdown
        - ca-certificates
        - apt-transport-https
        - gnupg
        - lsb-release
        - kubelet
        - kubeadm
        - kubectl
        - containerd.io
      state: latest

  - name: Generate Default Containerd Config
    raw: containerd config default | sudo tee /etc/containerd/config.toml

  - name: Add Systemd as the cgroup driver for containerd
    ansible.builtin.lineinfile:
      state: present
      path: /etc/containerd/config.toml
      insertafter: '          \[plugins.\"io.containerd.grpc.v1.cri\".containerd.runtimes.runc.options\]'
      line: '            SystemdCgroup = true'

  handlers:
  - name: Autoremove Packages using APT
    ansible.builtin.apt:
      autoremove: yes
      purge: yes
