---
- name: Master Node Configuration
  hosts: all
  remote_user: root
  tasks:
  - name: Add Kernel Modules to Load
    ansible.builtin.lineinfile:
      path: /etc/modules-load.d/k8s-bootstrap.conf
      state: present
      create: yes
      line: "{{ item }}"
    loop:
      - br_netfilter
      - overlay

  - name: Add sysctl params
    ansible.builtin.lineinfile:
      path: /etc/sysctl.d/k8s-bootstrap.conf
      state: present
      create: yes
      line: "{{ item }}"
    loop:
      - net.bridge.bridge-nf-call-iptables = 1
      - net.ipv4.ip_forward = 1
      - net.bridge.bridge-nf-call-ip6tables = 1

  - name: Install the latest version of Kubelet Kubeadm Kubectl and Containerd
    ansible.builtin.package:
      name:
        - kubelet
        - kubeadm
        - kubectl
        - containerd.io
      state: latest

  - name: Generate Default Containerd Config
    raw: containerd config default | sudo tee /etc/containerd/config.toml

  - name: Add Systemd as the cgroup driver for containerd
    ansible.builtin.lineinfile:
      state: present
      path: /etc/containerd/config.toml
      insertafter: '          \[plugins.\"io.containerd.grpc.v1.cri\".containerd.runtimes.runc.options\]'
      line: '            SystemdCgroup = true'
